### ISSUE TITLE
X-input broken / not working with XboxOne wireless controller

### ISSUE THREAD

**Issue by jvhellraiser** [Jhno591/citra-2#4]
![capture](https://user-images.githubusercontent.com/16488761/28745921-84946af6-7450-11e7-86d5-a62822f41549.JPG)
Version : Citra.BE-GCC-MinGW-21-07-2017

I had notice that X-input is broken in this build i remember i did configure it
before in older versions you release but not in the new release, citra-2 wont even recognize 
the XboxOne controller the only way to make it work is by using and older version of qt-config.ini 
that was pre config with the XboxOne controller keys and when you access the input menu you will
see a None Keyboard where the keys should be, i manage to upload a JPG file so you can see.

**Comment by Jhno591** [comment]
jroweboy is working on a new branch
https://gbatemp.net/threads/citra-new-3ds-emulator.365154/page-339#post-7461596

I used the xbox360 pad, but had yes issues auto x-input , but can be fixed manually in the qt-config.ini file, for now please see - https://community.citra-emu.org/t/temporary-controller-configurations-for-citra/1061

Sorry I don't have a XboxOne controller to test, hope someone can help you there,

All best.
